# Generated by Django 4.2.11 on 2024-05-02 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_geeksmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Showroom',
        ),
    ]
